version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moviedb
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - movie_net

  elasticsearch:
    image: elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - movie_net

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - movie_net

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/public/posters:/app/public/posters
    depends_on:
      - backend
    networks:
      - movie_net

volumes:
  pg_data:
  es_data:

networks:
  movie_net: