# Generated by Django 4.2 on 2025-02-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
