# Generated by Django 4.2 on 2025-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_movie_plot_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plot_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
