# Generated by Django 4.2 on 2025-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_comment_rating_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reviews',
            field=models.JSONField(default=list),
        ),
    ]
